//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RelationDB : DbContext
    {
        public RelationDB()
            : base("name=RelationDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategoryType> tblCategoryTypes { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerCategory> tblCustomerCategories { get; set; }
        public virtual DbSet<tblCustomerCustomercategory> tblCustomerCustomercategories { get; set; }
        public virtual DbSet<tblCustomerPerson> tblCustomerPersons { get; set; }
        public virtual DbSet<tblCustomerPersonCategory> tblCustomerPersonCategories { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblOrderUnit> tblOrderUnits { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblSubscription> tblSubscriptions { get; set; }
        public virtual DbSet<tblSubscriptionTypeCustomer> tblSubscriptionTypeCustomers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserGroup> tblUserGroups { get; set; }
        public virtual DbSet<tblUserGroupUser> tblUserGroupUsers { get; set; }
    }
}
