//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public tblCompany()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblOrders = new HashSet<tblOrder>();
            this.tblOrderUnits = new HashSet<tblOrderUnit>();
            this.tblSubscriptions = new HashSet<tblSubscription>();
            this.tblUserGroups = new HashSet<tblUserGroup>();
        }
    
        public int companyID { get; set; }
        public string strName { get; set; }
    
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual ICollection<tblOrderUnit> tblOrderUnits { get; set; }
        public virtual ICollection<tblSubscription> tblSubscriptions { get; set; }
        public virtual ICollection<tblUserGroup> tblUserGroups { get; set; }
    }
}
