//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerPersonCategory
    {
        public int customerPersonCategoryID { get; set; }
        public int customerPersonID { get; set; }
        public int categoryID { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblCustomerPerson tblCustomerPerson { get; set; }
    }
}
