//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int messageID { get; set; }
        public string strMessage { get; set; }
        public Nullable<System.DateTime> dtmFrom { get; set; }
        public Nullable<System.DateTime> dtmTom { get; set; }
    }
}
