//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int orderID { get; set; }
        public int companyID { get; set; }
        public int userID { get; set; }
        public int customerID { get; set; }
        public Nullable<int> customerPersonID { get; set; }
        public Nullable<int> productID { get; set; }
        public int orderUnitID { get; set; }
        public Nullable<int> intAmount { get; set; }
        public Nullable<double> dblUnitPrice { get; set; }
        public string strDescription { get; set; }
        public bool bitInvoice { get; set; }
        public bool bitInvoiceOK { get; set; }
        public System.DateTime dtmWhen { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomerPerson tblCustomerPerson { get; set; }
        public virtual tblOrderUnit tblOrderUnit { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
