//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblOrders = new HashSet<tblOrder>();
            this.tblSubscriptions = new HashSet<tblSubscription>();
        }
    
        public int productID { get; set; }
        public int companyID { get; set; }
        public string strName { get; set; }
        public double dblUnitPrice { get; set; }
        public string strDescription { get; set; }
        public bool bitDisabled { get; set; }
    
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual ICollection<tblSubscription> tblSubscriptions { get; set; }
    }
}
