//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubscriptionTypeCustomer
    {
        public int subscriptionTypeCustomerID { get; set; }
        public Nullable<int> subscriptionTypeID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<System.DateTime> dtmStart { get; set; }
        public Nullable<System.DateTime> dtmStop { get; set; }
        public Nullable<System.DateTime> dtmInvoice { get; set; }
        public Nullable<int> intAmount { get; set; }
        public Nullable<int> intInvoiceInterval { get; set; }
    }
}
