//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubscription
    {
        public int subscriptionID { get; set; }
        public int companyID { get; set; }
        public int customerID { get; set; }
        public int customerPersonID { get; set; }
        public int productID { get; set; }
        public int intInvoicesPerYear { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomerPerson tblCustomerPerson { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
