//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroup
    {
        public tblUserGroup()
        {
            this.tblUserGroupUsers = new HashSet<tblUserGroupUser>();
        }
    
        public int userGroupID { get; set; }
        public int companyID { get; set; }
        public string strName { get; set; }
        public bool bitDisabled { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual ICollection<tblUserGroupUser> tblUserGroupUsers { get; set; }
    }
}
