//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblOrders = new HashSet<tblOrder>();
            this.tblUserGroupUsers = new HashSet<tblUserGroupUser>();
        }
    
        public int userID { get; set; }
        public int companyID { get; set; }
        public string strFirstname { get; set; }
        public string strLastname { get; set; }
        public string strUsername { get; set; }
        public string strEmail { get; set; }
        public string strPassword { get; set; }
        public bool bitDisabled { get; set; }
    
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual ICollection<tblUserGroupUser> tblUserGroupUsers { get; set; }
    }
}
